apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-laravel-app
  template:
    metadata:
      labels:
        app: my-laravel-app
    spec:
      containers:
      - name: my-laravel-app
        image: <your-dockerhub-username>/my-laravel-app:latest
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: my-laravel-app-service
spec:
  selector:
    app: my-laravel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer

