apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: app
          image: your-docker-registry/laravel-app:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: app-storage
              mountPath: /var/www/storage
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
